version: "3.7"
services:
  mysql_drycleaning:
    image: mysql:5.7
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root3004917779
      MYSQL_USER: yurijmo
      MYSQL_PASSWORD: 3004917779
      MYSQL_DATABASE: db_drycleaning
    networks:
      - backend
    container_name: mysql_drycleaning
  phpmyadmin_drycleaning:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_drycleaning
    ports:
      - 2323:80
    links:
      - mysql_drycleaning:db
    networks:
      - backend
networks:
  frontend:
  backend:
volumes:
  data:
